name: Format PR

on:
  pull_request:
    branches: [ master ]

jobs:
  format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Configure git
      run: |
        git config user.name "Github Actions Bot"
        git config user.email "<>"
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Check Python formatting
      id: check-python
      continue-on-error: true
      run: |
        black . --check
    - name: Commit formatting changes
      if: ${{ steps.check-python.outcome == 'failure' }}
      run: |
        black .
        git add .
        git commit -m "Format with Black"
        git push
